# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-21 06:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollSys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_fee',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='fees_paid',
            field=models.BooleanField(default=True),
        ),
    ]
